from .user import User
from .student import Student
from .department import Department
from .faculty import Faculty
from .course import Course
from .attendance import Attendance
from .exam import Exam
from .result import Result
from .fee import Fee
from .timetable import Timetable
from .assignment import Assignment